SRCS+=	bcopy.c index.c memchr.c memcmp.c memcpy.c memmove.c memset.c rindex.c stpcpy.c stpncpy.c strcat.c strchr.c strchrnul.c \
	strcmp.c strcpy.c strcasecmp.c strcasestr.c strlcat.c strlcpy.c strlen.c strncasecmp.c strncat.c strncmp.c strncpy.c \
	strnlen.c strnstr.c strrchr.c strstr.c

MAN+=	bcopy.3 index.3 memchr.3 memcmp.3 memcpy.3 memmove.3 memset.3 rindex.3 stpcpy.c stpncpy.3 strcat.3 strchr.c strchrnul.3 \
	strcmp.3 strcpy.3 strcasecmp.3 strcasestr.3 strlcat.3 strlcpy.3 strlen.3 strncasecmp.3 strncat.3 strncmp.3 strncpy.3 \
	strnlen.3 strnstr.3 strrchr.3 strstr.3
