SRCS+=	bcopy.c bzero.c consttime_memequal.c memchr.c memccpy.c memcmp.c memcpy.c memmem.c memmove.c \
	mempcpy.c memrchr.c memset.c stpcpy.c stpncpy.c strcat.c strchr.c strchrnul.c strcmp.c strcpy.c \
	strcspn.c strcasecmp.c strcasestr.c strlcat.c strlcpy.c strlen.c strncasecmp.c strncat.c strncmp.c \
	strncpy.c strnlen.c strnstr.c strpbrk.c strrchr.c strsep.c strspn.c strstr.c strtok.c strtok_r.c

MAN+=	bcopy.3 bzero.3 consttime_memequal.3 index.3 memchr.3 memccpy.3 memcmp.3 memcpy.3 memmem.3 memmove.3 \
	mempcpy.3 memrchr.3 memset.3 rindex.3 stpcpy.3 stpncpy.3 strcat.3 strchr.3 strchrnul.3 strcmp.3 strcpy.3 \
	strcspn.3 strcasecmp.3 strcasestr.3 strlcat.3 strlcpy.3 strlen.3 strncasecmp.3 strncat.3 strncmp.3 \
	strncpy.3 strnlen.3 strnstr.3 strpbrk.3 strrchr.3 strsep.3 strspn.3 strstr.3 strtok.3 strtok_r.3
