STRING := $(wildcard string/*.c)
CTYPE := $(wildcard ctype/*.c)
LINUX := $(wildcard linux/*.c)
GEN := $(wildcard gen/*.c)
STDLIB := $(wildcard stdlib/*.c)
COMPAT_OPENBSD := $(wildcard compat/OpenBSD/*.c)
COMPAT_NETBSD := $(wildcard compat/NetBSD/*.c)
COMPAT := $(COMPAT_OPENBSD) $(COMPAT_NETBSD)

GENERAL_INCLUDES := $(wildcard include/*.h)
SYSTEM_INCLUDES := $(wildcard include/sys/*.h)
MACHINE_INCLUDES := $(wildcard arch/$(MACHINE)/machine/*.h)

ALL_SRCS := $(STRING) $(CTYPE) $(LINUX) $(GEN) $(STDLIB) $(COMPAT)
ALL_OBJS := $(ALL_SRCS:%.c=%.o)
