INCS=	libgen.h stdint.h sys/common_int_const.h sys/common_int_limits.h common_int_mwgwtypes.h \
	sys/common_int_types.h common_wchar_limits.h sys/featuretest.h sys/null.h sys/stdint.h \
	sys/syscall.h sys/utsname.h

# WIK
# assert.h
# ctype.h
# limits.h
# stddef.h
# string.h
# unistd.h
# sys/cdefs.h
# sys/param.h
# sys/types.h
