INCS=	libgen.h limits.h stdbool.h stdint.h sys/cdefs.h sys/cdefs_elf.h sys/common_int_const.h \
	sys/common_int_limits.h common_int_mwgwtypes.h sys/common_int_types.h common_wchar_limits.h \
	sys/featuretest.h sys/null.h sys/stdbool.h sys/stdint.h sys/syscall.h sys/syslimits.h sys/utsname.h

# WIK
# assert.h
# ctype.h
# stddef.h
# string.h
# unistd.h
# sys/param.h
# sys/types.h
