INCS=	libgen.h stdint.h sys/common_int_limits.h sys/common_int_types.h sys/featuretest.h sys/null.h \
	sys/stdint.h sys/utsname.h

# WIK
# assert.h
# ctype.h
# limits.h
# stddef.h
# string.h
# unistd.h
# sys/cdefs.h
# sys/param.h
# sys/types.h
